#assign_app_label_pe2.yaml
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2pe21ocp01-ien01
      labels:
        pe2/app: istio
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2pe21ocp01-ien02
      labels:
        pe2/app: istio
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2pe21ocp01-ien03
      labels:
        pe2/app: istio
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2pe21ocp01-evs01
      labels:
        pe2/app: eventstream
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2pe21ocp01-evs02
      labels:
        pe2/app: eventstream
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2pe21ocp01-evs03
      labels:
        pe2/app: eventstream
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2pe21ocp01-wrk01
      labels:
        pe2/app: ilgw
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2pe21ocp01-wrk02
      labels:
        pe2/app: ilgw
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2pe21ocp01-wrk03
      labels:
        pe2/app: ilgw
