#assign_app_label_TAC.yaml
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2tac1ocp01-ien01
      labels:
        app: istio
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2tac1ocp01-ien02
      labels:
        app: istio
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2tac1ocp01-ien03
      labels:
        app: istio
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2tac1ocp01-evs01
      labels:
        app: eventstream
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2tac1ocp01-evs02
      labels:
        app: eventstream
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2tac1ocp01-evs03
      labels:
        app: eventstream
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2tac1ocp01-wrk01
      labels:
        app: ilgw
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2tac1ocp01-wrk02
      labels:
        app: ilgw
  - apiVersion: v1
    kind: Node
    metadata:
      name: sis2tac1ocp01-wrk03
      labels:
        app: ilgw
